services:
  mysql:
    image: mysql:8.0
    container_name: github-pr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: github_prs
      MYSQL_USER: pruser
      MYSQL_PASSWORD: prpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-pr-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=pruser
      - DB_PASSWORD=prpassword
      - DB_NAME=github_prs
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOS=${GITHUB_REPOS}
      - FETCH_SINCE_DAYS=${FETCH_SINCE_DAYS:-30}
    volumes:
      - ./:/app

  web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: github-pr-web-ui
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=pruser
      - DB_PASSWORD=prpassword
      - DB_NAME=github_prs
    depends_on:
      - mysql
      - app
    volumes:
      - ./web-ui:/app

  # New service for scheduled updates
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-pr-scheduler
    command: sh -c "while true; do /app/github-pr-tracker; sleep ${UPDATE_INTERVAL:-3600}; done"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=pruser
      - DB_PASSWORD=prpassword
      - DB_NAME=github_prs
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOS=${GITHUB_REPOS}
      - FETCH_SINCE_DAYS=${FETCH_SINCE_DAYS:-30}
    volumes:
      - ./:/app

volumes:
  mysql-data: